language: php

php:
  # Silverstripe 4
  - 5.6

env:
  matrix:
    - DB=MYSQL CORE_RELEASE=4

matrix:
  include:
    - php: 5.6
      env:
        - RECIPE_VERSION=1.0.x-dev
        - DB=MYSQL
        - PHPCS_TEST=1
    - php: 7.0
      env:
        - RECIPE_VERSION=1.1.x-dev
        - DB=PGSQL
    - php: 7.1
      env:
        - RECIPE_VERSION=4.2.x-dev
        - DB=MYSQL
        - PDO=1
    - php: 7.2
      env:
        - RECIPE_VERSION=4.x-dev
        - DB=MYSQL
        - PDO=1

before_script:
  - phpenv rehash
  - phpenv config-rm xdebug.ini
  - composer validate
  - composer require --no-update silverstripe/recipe-cms:$RECIPE_VERSION
  - if [[ $DB == PGSQL ]]; then composer require --no-update silverstripe/postgresql:2.0.x-dev; fi
  - composer install --prefer-dist --no-interaction --no-progress --no-suggest --optimize-autoloader --verbose --profile

script:
  - vendor/bin/phpunit
  - if [[ $PHPCS_TEST ]]; then vendor/bin/phpcs --standard=vendor/silverstripe/framework/phpcs.xml.dist src/ tests/ ; fi
